### ISSUE TITLE
Aspect per meta class of aspect als unieke properties

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#54]
In het originele MiM document komen bepaalde aspecten terug bij verschillende metaclasses. In RDF is het gebruikelijk om deze aspecten maar 1 keer de definiëren. Probleem hierbij is dat de namen wel uniek zijn, maar de definities wijken deels af. Vaak is dit slechts contextueel (bv: "De naam van het objecttype" versus "De naam van de attribuutsoort"), soms wordt extra uitleg of extra regels gegeven in de definitie (bv: "De naam van de lijst zoals gespecificeerd in de catalogus van de desbetreffende registratie dan wel, indien het een door de eigen organisatie toegevoegde lijst betreft, de door de eigen organisatie vastgestelde naam.")

Voorstel:
- [ ] Splitsen van de definities in een algemene definitie en een contextuele definitie. Deze laatste kan dan bij de shape opgenomen worden, de eerste kan dan opgenomen worden bij de property (het aspect) zelf.
- [ ] Dit betekent overigens wel dat in het originele MiM document een overzicht van alle aspecten, los van metaclass, opgenomen moet worden met deze definities.
- [ ] In afzonderlijke issues zal een voorstel gedaan worden van de algemene definitie, voor die situaties dat er ambiguïteit is ontstaan.

**Comment by JvG-GNM** [comment]
Dit is het "oude" issue nummer 6 uit de bp4mc2 repository. Er wordt door een aantal van de overgezette issues naar verwezen. het issuenummer is nu 54

**Comment by lennartvanbergen-kadaster** [comment]
Alle metadata aspecten hebben een definitie/toelichting, die - als er sprake is van een algemeen/vaker terugkerend metadata aspect - via een link uit moet komen bij: paragraaf 2.3.1. Algemene metadata aspecten. De oude paragraaf 2.3.1. wordt 2.3.2. en 2.3.2 wordt 2.3.3 etc

Dit kan voor al deze worden doorgevoerd.
